### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by theogf** [JuliaGaussianProcesses/KernelFunctions.jl#105]
It would nice to have a first 1.x.x release. With the latest change it feels we have a first stable implementation.
Here is what I think is missing so far :
- [ ] Rework the documentation #101, #100, #98 #97 #96 #93 #92 #90
- [ ] Solves the issues raised during the last PRs #
- [ ] Implement some more advanced examples #11 
- [ ] Solve the refactoring of KernelSum/KernelProduct #68 #73 
- [ ] Finish the @kernel macro (if we still want to have it ?) #38 
- [ ] Tackle smaller issues #65 #47 #64
Any points to add ?

**Comment by willtebbutt** [comment]
Thanks for opening this. In no particular order:

- I'm not sure that I would put #98 under reworking the documentation, and it would be breaking if we modify that after 1.0. Could we put that as a separate point to be resolved?
- Same with #93 -- I'm not sure that the current API is the right way to go about things, particularly now that we have the `TensorProduct` kernel. Would be better as a separate point

Otherwise I think this list looks reasonable. The most important thing is that we're able to commit to whatever interface we have. We can do things like ensure compatibility with AD in future releases.

**Comment by theogf** [comment]
Ups look like I mixed things up. I will edit now

**Comment by willtebbutt** [comment]
Great, in that case I'm pretty happy with it!

**Comment by willtebbutt** [comment]
Could you make one of those milestone things with a link to each of the issue in?

**Comment by theogf** [comment]
Done. Actually milestones are different from projects
