### ISSUE TITLE
Userguide improvements

### ISSUE THREAD

**Issue by st--** [JuliaGaussianProcesses/KernelFunctions.jl#221]
- [ ] Lengthscales & transforms (see #217)
- [ ] Documentation of TensorProduct (from #213)
- [ ] Discussion around Functors.functor (from #213)
